### ISSUE TITLE
No plus sign to expand objects

### ISSUE THREAD

**Issue by noulis** [smuyyh/JsonViewer#4]
Hello smuyyh,

i have used your library in an activity of my app in order to show a pretty big json object with several nested levels.

In the beginning I observed a plus sign at the left of each object that let me expand the object values by pressing it. 

As of today, I have lost this plus sign. It is not shown at all. However, if I press the placeholder of the plus sign I can indeed expand the items. But not having the plus sign there is a UI difficulty.

Are you aware of this issue?

Thank you in advance,
Kostas

**Comment by smuyyh** [comment]
the plus sign is use iconfont which in /assets/icomoon.ttf, did you delete it?

**Comment by noulis** [comment]
No, I have not deleted it. I just checked and the icomoon.ttf is in my project.

Only the plus sign has been removed. The minus sign is there.

FYI: I just imported the library, i did not do any further changes.

**Comment by smuyyh** [comment]
update dependencies to 1.0.5 and try it~   I review the code, and I didn't find any problems

**Comment by mikepenz** [comment]
Just came across this library and saw the issue. I have a library which is also working with icon fonts for android. Sometimes it happens that the unicode character used by the font is not supported on some devices (or android versions) or overlapped due to some encoding topics. (Actually I was never able to identify a real pattern behind this). For the font's I used remapping to different unicode characters worked.

**Comment by smuyyh** [comment]
@mikepenz Thanks.  @noulis You can try remapping and see if it can be solved.

**Comment by smuyyh** [comment]
resolved~
